"""
mlpilot/deploy/launchpad.py
LaunchPad — generate a FastAPI app, Dockerfile, and Streamlit dashboard
from a trained model in under 5 minutes.
"""

from __future__ import annotations

import os
import pickle
from pathlib import Path
from typing import Any, Optional

import pandas as pd

from mlpilot.utils.display import print_step, print_success, print_warning


_FASTAPI_MAIN_TEMPLATE = '''"""
Auto-generated FastAPI prediction API — mlpilot LaunchPad
Model: {model_name} v{version}
"""

import pickle
from pathlib import Path
from typing import Dict, List, Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(
    title="{model_name} Prediction API",
    description="Auto-generated by mlpilot LaunchPad",
    version="{version}",
)

app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"]
)

# Load model
MODEL_PATH = Path(__file__).parent / "model.pkl"
with open(MODEL_PATH, "rb") as f:
    MODEL = pickle.load(f)

FEATURE_NAMES = {feature_names!r}


class PredictionRequest(BaseModel):
    features: Dict[str, Any]


class PredictionResponse(BaseModel):
    prediction: Any
    confidence: str


class BatchRequest(BaseModel):
    rows: List[Dict[str, Any]]


@app.get("/health")
def health():
    return {{"status": "healthy", "model": "{model_name}", "version": "{version}"}}


@app.get("/model-info")
def model_info():
    return {{
        "model_name": "{model_name}",
        "version": "{version}",
        "feature_names": FEATURE_NAMES,
        "n_features": len(FEATURE_NAMES),
    }}


@app.post("/predict", response_model=PredictionResponse)
def predict(request: PredictionRequest):
    import pandas as pd
    try:
        row = pd.DataFrame([request.features])
        prediction = MODEL.predict(row)[0]
        confidence = "high"
        if hasattr(MODEL, "predict_proba"):
            proba = MODEL.predict_proba(row)[0]
            max_prob = float(max(proba))
            confidence = "high" if max_prob > 0.8 else "medium" if max_prob > 0.6 else "low"
        return PredictionResponse(prediction=str(prediction), confidence=confidence)
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.post("/predict/batch")
def predict_batch(request: BatchRequest):
    import pandas as pd
    try:
        df = pd.DataFrame(request.rows)
        predictions = MODEL.predict(df).tolist()
        return {{"predictions": predictions, "count": len(predictions)}}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.post("/feedback")
def feedback(prediction_id: str, actual_label: Any):
    # Log prediction feedback for drift monitoring
    return {{"status": "logged", "prediction_id": prediction_id}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

_DOCKERFILE_TEMPLATE = '''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''

_DOCKER_COMPOSE_TEMPLATE = '''version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model.pkl
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
'''

_REQUIREMENTS_TEMPLATE = '''fastapi>=0.100.0
uvicorn>=0.23.0
scikit-learn>=1.2.0
pandas>=1.5.0
numpy>=1.23.0
pydantic>=2.0.0
'''

_STREAMLIT_TEMPLATE = '''"""
Auto-generated Streamlit dashboard — mlpilot LaunchPad
"""

import pickle
import pandas as pd
import streamlit as st

st.set_page_config(page_title="{model_name} Dashboard", page_icon="🚀", layout="wide")

st.title("🚀 {model_name} — Prediction Dashboard")
st.markdown("*Auto-generated by mlpilot LaunchPad*")

# Load model
@st.cache_resource
def load_model():
    with open("model.pkl", "rb") as f:
        return pickle.load(f)

model = load_model()
feature_names = {feature_names!r}

st.sidebar.header("Input Features")
features = {{}}
for feat in feature_names:
    features[feat] = st.sidebar.number_input(feat, value=0.0)

if st.button("🔮 Predict", type="primary"):
    df = pd.DataFrame([features])
    prediction = model.predict(df)[0]
    st.success(f"Prediction: **{{prediction}}**")
    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(df)[0]
        st.bar_chart(pd.DataFrame({{"Probability": proba}}))
'''


class LaunchPad:
    """
    Model deployment generator.
    Created by ml.deploy(model, X_sample=...).
    """

    def __init__(
        self,
        model: Any,
        X_sample: Optional[pd.DataFrame] = None,
        model_name: str = "mlpilot_model",
        version: str = "1.0.0",
    ):
        self.model = model
        self.X_sample = X_sample
        self.model_name = model_name
        self.version = version
        self.feature_names = list(X_sample.columns) if X_sample is not None else []

    def generate_api(self, output_dir: str = "./api") -> str:
        """Generate a FastAPI application in the given directory."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        # main.py
        main_py = _FASTAPI_MAIN_TEMPLATE.format(
            model_name=self.model_name,
            version=self.version,
            feature_names=self.feature_names,
        )
        (out / "main.py").write_text(main_py, encoding="utf-8")

        # requirements.txt
        (out / "requirements.txt").write_text(_REQUIREMENTS_TEMPLATE, encoding="utf-8")

        # Save model
        model_path = out / "model.pkl"
        with open(model_path, "wb") as f:
            pickle.dump(self.model, f)

        print_success(f"FastAPI app generated → {out.resolve()}")
        print_step("Run: cd " + str(out) + " && uvicorn main:app --reload", "🚀")
        return str(out.resolve())

    def generate_docker(self, output_dir: str = "./api") -> str:
        """Generate Docker files in the given directory."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        (out / "Dockerfile").write_text(_DOCKERFILE_TEMPLATE, encoding="utf-8")
        (out / "docker-compose.yml").write_text(_DOCKER_COMPOSE_TEMPLATE, encoding="utf-8")
        (out / ".dockerignore").write_text("__pycache__/\n*.pyc\n.env\n", encoding="utf-8")

        print_success(f"Docker files generated → {out.resolve()}")
        print_step("Run: docker-compose up --build", "🐳")
        return str(out.resolve())

    def generate_dashboard(self, output_dir: str = "./dashboard") -> str:
        """Generate a Streamlit dashboard."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        dash_py = _STREAMLIT_TEMPLATE.format(
            model_name=self.model_name,
            feature_names=self.feature_names,
        )
        (out / "app.py").write_text(dash_py, encoding="utf-8")

        model_path = out / "model.pkl"
        with open(model_path, "wb") as f:
            pickle.dump(self.model, f)

        print_success(f"Streamlit dashboard generated → {out.resolve()}")
        print_step("Run: streamlit run " + str(out / "app.py"), "📊")
        return str(out.resolve())

    def serve(self, port: int = 8000, host: str = "0.0.0.0") -> None:
        """Start the FastAPI server locally."""
        import tempfile
        tmp_dir = tempfile.mkdtemp(prefix="mlpilot_")
        self.generate_api(tmp_dir)
        print_step(f"Starting server at http://localhost:{port}", "🌐")
        print_step(f"Swagger UI: http://localhost:{port}/docs", "📚")
        try:
            import uvicorn
            import sys
            sys.path.insert(0, tmp_dir)
            from main import app
            uvicorn.run(app, host=host, port=port)
        except ImportError:
            print_warning("uvicorn not installed — install with: pip install mlpilot[deploy]")
            print_step(f"Generated app in: {tmp_dir}", "📁")

    def export(self, path: str) -> str:
        """Export the model in the specified format (.pkl, .joblib, .onnx)."""
        if path.endswith(".pkl"):
            with open(path, "wb") as f:
                pickle.dump(self.model, f)
            print_success(f"Model exported as pickle → {path}")
        elif path.endswith(".joblib"):
            import joblib
            joblib.dump(self.model, path)
            print_success(f"Model exported as joblib → {path}")
        elif path.endswith(".onnx"):
            print_warning("ONNX export coming in v0.3.0")
        else:
            print_warning(f"Unknown format: {path}")
        return path

    def __repr__(self) -> str:
        return (f"LaunchPad(model={type(self.model).__name__}, "
                f"name={self.model_name!r}, version={self.version!r})")


def deploy(
    model: Any,
    X_sample: Optional[pd.DataFrame] = None,
    model_name: str = "mlpilot_model",
    version: str = "1.0.0",
) -> LaunchPad:
    """
    LaunchPad — Model Deployment.

    Go from a trained model to a running REST API in under 5 minutes.
    Generates a FastAPI app, Dockerfile, schema, and Streamlit dashboard.

    Parameters
    ----------
    model : sklearn-compatible fitted estimator
    X_sample : pd.DataFrame, optional
        Sample of input data — used to infer feature names.
    model_name : str
        Name for the model/API.
    version : str
        API version string.

    Returns
    -------
    LaunchPad
        Methods: generate_api(), generate_docker(), generate_dashboard(),
        serve(port=8000), export('model.pkl').

    Examples
    --------
    >>> import mlpilot as ml
    >>> launcher = ml.deploy(model, X_sample=X_test.iloc[:10])
    >>> launcher.generate_api('./api')
    >>> launcher.generate_docker('./api')
    >>> launcher.serve(port=8000)
    """
    print_step(f"LaunchPad: preparing deployment for {type(model).__name__}", "🚀")
    return LaunchPad(model=model, X_sample=X_sample,
                     model_name=model_name, version=version)
