"""
mlpilot/pipeline/recorder.py
PipelineRecorder — records all mlpilot operations in a session
and exports them as a reproducible notebook or script.
"""

from __future__ import annotations

import json
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, List, Optional

from mlpilot.utils.display import print_step, print_success


class PipelineRecorder:
    """
    Records all mlpilot operations performed in a session.
    Created by ml.session() context manager.

    Usage:
        with ml.session('churn_v1') as sess:
            eda = ml.analyze(df, target='churn')
            clean = ml.clean(df, target='churn')
            ...
        sess.export_script('pipeline.py')
        sess.export_notebook('pipeline.ipynb')
    """

    def __init__(self, name: str = "mlpilot_session"):
        self.name = name
        self._operations: List[Dict] = []
        self._start_time = time.time()

    def record(self, operation: str, args: str, result_type: str = "") -> None:
        self._operations.append({
            "operation": operation,
            "args": args,
            "result_type": result_type,
            "timestamp": time.time() - self._start_time,
        })

    def export_script(self, path: str = "pipeline.py") -> str:
        """Export the session as a standalone Python script."""
        lines = [
            "# mlpilot — Auto-generated Pipeline",
            f"# Session: {self.name}",
            "# Generated by mlpilot PipelineRecorder",
            "",
            "import mlpilot as ml",
            "import pandas as pd",
            "",
        ]
        for op in self._operations:
            lines.append(f"# Step: {op['operation']}")
            lines.append(f"result_{op['operation'].replace('.', '_')} = {op['args']}")
            lines.append("")

        script = "\n".join(lines)
        out_path = Path(path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(script, encoding="utf-8")
        print_success(f"Script exported → {out_path.resolve()}")
        return str(out_path.resolve())

    def export_notebook(self, path: str = "pipeline.ipynb") -> str:
        """Export the session as a Jupyter notebook."""
        cells = [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"# mlpilot Pipeline — {self.name}\n",
                           "Auto-generated by mlpilot PipelineRecorder"],
            },
            {
                "cell_type": "code",
                "metadata": {},
                "source": ["import mlpilot as ml\nimport pandas as pd\n"],
                "outputs": [],
                "execution_count": None,
            },
        ]
        for op in self._operations:
            cells.append({
                "cell_type": "code",
                "metadata": {},
                "source": [f"# {op['operation']}\n", op["args"]],
                "outputs": [],
                "execution_count": None,
            })

        nb = {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                "language_info": {"name": "python", "version": "3.9.0"},
            },
            "cells": cells,
        }
        out_path = Path(path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as f:
            json.dump(nb, f, indent=2)
        print_success(f"Notebook exported → {out_path.resolve()}")
        return str(out_path.resolve())

    def export_pipeline(self, path: str = "pipeline.pkl") -> str:
        """Export the sklearn Pipeline object (if available)."""
        print_step(f"Pipeline export to '{path}' — available in v0.2.0", "⏳")
        return path

    def export_report(self, path: str = "session_report.pdf") -> str:
        """Export a PDF summary report of the session."""
        print_step(f"PDF report '{path}' — available in v0.2.0", "⏳")
        return path

    def __repr__(self) -> str:
        return f"PipelineRecorder(name={self.name!r}, n_operations={len(self._operations)})"


# ---------------------------------------------------------------------------
# Context manager
# ---------------------------------------------------------------------------

@contextmanager
def session(name: str = "mlpilot_session", verbose: bool = True):
    """
    PipelineRecorder context manager.
    Records all mlpilot operations performed inside the block.

    Usage:
        with ml.session('churn_v1') as sess:
            eda = ml.analyze(df, target='churn')
            clean = ml.clean(df, target='churn')
        sess.export_script('pipeline.py')
        sess.export_notebook('pipeline.ipynb')
    """
    recorder = PipelineRecorder(name=name)
    if verbose:
        print_step(f"Session '{name}' started", "🎬")
    try:
        yield recorder
    finally:
        elapsed = time.time() - recorder._start_time
        if verbose:
            print_success(
                f"Session '{name}' complete — "
                f"{len(recorder._operations)} operations in {elapsed:.1f}s"
            )
